language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='OpenJDK 13'
      install: . ./install-jdk.sh -F 13 -L GPL

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - mvn spotless:check
  - mvn -X clean install

jdk:
 - openjdk13
