package com.aether.model;

/**
 * Represents an abstract technology.
 */
public interface Technology {
    /**
     * The name of this technology, e.g.: 'Terraforming Module'.
     *
     * @return the name of the technology.
     */
    String getName();

    /**
     * Gets the name of the category this technology is in.
     * E.g.: 'Biology/Genetics' or 'Power and Propulsion', etc.
     *
     * @return the category of the technology.
     */
    String getCategory();

    /**
     * Gets the cost of the technology in Research Points.
     * Research Points are an arbitrary resource, generated by Research Labs.
     *
     * @return the cost of the technology.
     */
    int getCost();
}
